services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5001:5000"
    depends_on:
      - database
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=allobbrico
      - DB_USER=postgres
      - DB_PASSWORD=password
      - JWT_SECRET=development_secret_key
    volumes:
      - ./backend:/app
      - /app/node_modules

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: allobbrico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@allobbrico.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
  pgadmin_data: