services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5001:5000"
    depends_on:
      - database
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@database:5432/allobbrico
      - JWT_SECRET=development_secret_key
    volumes:
      - ./backend:/app
      - /app/node_modules

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: allobbrico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data: